### ISSUE TITLE
Support for mysql type databases

### ISSUE THREAD

**Issue by micheasherman-minted** [Ticketmaster/techmaturity#9]
This would be much easier to deploy and maintain if it could talk to a mysql type database. (especially the docker instance.)

**Comment by vigneshjb** [comment]
@micheasherman-minted : Thanks for testing out Techmaturity. We are working on adding support for data persistence in a simple way. I'll keep updating the issue as we make progress. In the mean time, I have added `pg` gem to the GemFile. Now, you should be able to use a Postgres database by supplying a custom `database.yml` config file.

for example :

Create a file called `database.yml` with :

```
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <Username for the database>
  password: <Password for the database>

development:
  <<: *default
  database: techmaturity_dev
  host: <A Postgres Database host URL>

test:
  <<: *default
  database: techmaturity_qa
  host: <A Postgres Database host URL>

production:
  <<: *default
  database: techmaturity_prod
  host: <A Postgres Database host URL>
```
and start the docker container by running the command :
```
docker run -p 3000:3000 -v `pwd`/database.yml:/techmaturity/config/database.yml ticketmaster/techmaturity:2.0.0
```

**Comment by micheasherman-minted** [comment]
That is working fine.

A note that 


```
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <Username for the database>
  password: <Password for the database>

production:
  <<: *default
  database: techmaturity
  host: postgress.example.com
```
Was the minimum file I was able to get started with
